# Site settings
title: Eugen Hotaj Blog

twitter_username: EugenHotaj 
github_username: EugenHotaj 
linkedin_username: eugen-hotaj 

# Build settings
theme: "minima"
markdown: kramdown
google_analytics: G-QN0DJ2RV4X
show_excerpts: True
plugins:
  - jekyll-feed
  - jekyll-seo-tag